# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [6]:
import numpy as np
line = np.random.randint(0,20, size = (4,7))
line

array([[ 0,  2,  5,  9, 19, 13, 14],
       [12, 12, 14,  6, 12,  0, 17],
       [ 5,  0, 19,  7,  7,  1,  8],
       [13,  2, 17,  5, 16, 17, 19]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
line_1 = np.random.randint(0,10, size = (8,10))
line_1

array([[8, 4, 6, 8, 2, 7, 0, 6, 9, 6],
       [6, 1, 8, 5, 6, 6, 1, 5, 6, 0],
       [7, 6, 0, 5, 3, 8, 0, 6, 1, 6],
       [5, 7, 8, 4, 2, 6, 9, 1, 3, 0],
       [5, 9, 0, 3, 4, 8, 1, 3, 2, 4],
       [0, 6, 3, 4, 5, 1, 4, 0, 2, 4],
       [8, 3, 5, 9, 1, 2, 9, 7, 7, 1],
       [0, 5, 5, 7, 7, 9, 5, 3, 9, 3]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [71]:
import numpy as np 
data = np.loadtxt('minutes_n_ingredients.csv', delimiter = ',', skiprows = 1, dtype =np.int32)
string = data[:5,:]
string

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
data_1 = data[:,1:]
means = np.mean(data_1, axis = 0)
mins = np.min(data_1, axis = 0)
maxs = np.max(data_1, axis = 0)
medians = np.median(data_1, axis = 0)

print("Means: ", means)
print("Mins: ", mins)
print("Maxs: ", maxs)
print("Medians: ", medians)

Means:  [2.16010017e+04 9.05528000e+00]
Mins:  [0 1]
Maxs:  [2147483647         39]
Medians:  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [9]:
data[:, 1] = np.clip(data[:, 1], 0, np.quantile(data[:, 1], 0.75))
print(data)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [50]:
print(len(data[data[:, 1] == 0]))
data[data[:, 1] == 0] = 1

479


In [51]:
print(len(data[data[:, 1] == 0]))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [48]:
len(np.unique(data[:, 0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [52]:
ingr = set(data[:, 2])
print(len(ingr))

37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [53]:
under_data = np.copy(data)
mask = (under_data[:, 2] <= 5)
under_data[mask, :]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [59]:
cost = data[:, 2] / data[:, 1]
print(cost.max(axis = 0))

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [60]:
data_sort = data[data[:, 1].argsort()]
data_sort = data_sort[-100:]
np.mean(data_sort[:, 2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [67]:
lst = np.random.randint(0, 100000, size = (1, 10))
print(data[lst])

[[[133780     40      5]
  [ 60352      5      6]
  [315878     15      5]
  [454451     55      8]
  [ 99570     50      5]
  [474128    200      9]
  [350029     60      7]
  [ 84810     10      8]
  [432054     45      9]
  [ 21421    150     15]]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [68]:
percent = (data[:, 2] <= np.mean(data[:, 2]))
len(data[percent, :])/len(data)*100                

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [72]:
simple_data = np.copy(data)
cost =[1 if line[1] <= 20 and line[2] <= 5 else 0 for line in simple_data]
simple_data = np.insert(simple_data, 3, values = cost, axis = 1)
simple_data

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [73]:
len(simple_data[(simple_data[:, 3] == 1)]) / len(data)*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.